### PR TITLE
Draft : Feature/sms output

### PR DESCRIPTION
**Pull request by mithunbharadwaj**

### CODE REVIEW

**Comment by mithunbharadwaj** [comment]
resolve conflict

**Comment by mithunbharadwaj** [comment]
@ateska Sample output with pdf attachment
Screenshot 2023-04-06 at 10 54 18

**Review by ateska — APPROVED** [review]
Looks OK to me ... be prepared to implement other SMS gateways in the future (aka Provider concept)

**Comment by ateska** [comment]
And please test this as discussed, ask someone from teams.

**Review by ateska — APPROVED** [review]

**Pull request merged**
