### PR TITLE
Beautify markdown to html output

### PR DESCRIPTION
**Pull request by mithunbharadwaj**

### CODE REVIEW

**Review by ateska — CHANGES_REQUESTED** [review]
This looks legit - but can I have some examples please.
Ideally in `/library` in this repository.

**Comment by mithunbharadwaj** [comment]
@ateska I have added a template to `/library/Email/`

Below is a sample output


Screenshot 2024-04-03 at 19 54 39

**Review by ateska — APPROVED** [review]

**Comment by ateska** [comment]
I need actually one more thing - the email markdown wrapper should be also configurable from the config.
It means that if I state a name of the template in the config, it will be applied to all markdown emails.

```
[email]
markdown_wrapper=/Templates/Wrappers/Email.html
```

**Comment by mithunbharadwaj** [comment]
@ateska you meant?

```
[smtp]
markdown_wrapper=/Templates/Wrappers/Email.html
```

**Comment by ateska** [comment]
`[email]` - it is not a SMTP.

**Pull request merged**
