### PR TITLE
Kafka handler : Fallback solution

### PR DESCRIPTION
**Pull request by mithunbharadwaj**

### CODE REVIEW

**Comment by ateska** [comment]
Ok, this look good to me.
I want sample outputs (emails, Slack messages) with illustration of these failing messages, please.

**Comment by mithunbharadwaj** [comment]
@ateska Some sample output from testing

Screenshot 2024-02-08 at 10 19 07
Screenshot 2024-02-08 at 10 19 55

**Comment by ateska** [comment]
Ok, good.

Can I see samples from email and MS teams too?

Thanks.

Then it seems to be mergeable.

**Comment by mithunbharadwaj** [comment]
@ateska Sure, 

I would like to more tests on Email use case too and I will send you both screen shots for both Email and MSTeams.

**Comment by mithunbharadwaj** [comment]
@ateska Email notifications from Kafka handler

Screenshot 2024-02-09 at 4 18 02
Screenshot 2024-02-09 at 4 20 20

**Comment by mithunbharadwaj** [comment]
@ateska MSTeams
Screenshot 2024-02-09 at 5 27 39

**Comment by mithunbharadwaj** [comment]
@ateska Improved message structure in MSTeams.

Screenshot 2024-02-09 at 10 42 59

**Review by ateska — APPROVED** [review]

**Pull request merged**
